### ISSUE TITLE
add --fetch-all option

### ISSUE THREAD

**Issue by emidoots** [bootradev/zig-fetch#1]
One drawback of using this compared to submodules is:

* It's often nice to be able to back up your entire project, without relying on external repositories still existing. With submodules it's easy to do a recursive clone of all submodules, and then e.g. zip up the entire directory. Today this isn't possible with zig-fetch unless you build the project, too, which is not ideal.
* I've heard this same desire/feedback from distro package maintainers ("the build system downloading things is concerning, can you ensure releases include everything needed to build from scratch?")

If zig-fetch had a `--fetch-all` flag, which worked recursively on all dependencies that may use fetch.zig themselves (without actually building the project), I think that'd solve this requirement.

**Comment by bootradev** [comment]
I think this one can be split into two parts: 

1) define how recursive dependencies work
2) provide a flag (fetch-only, I'm thinking) that is the opposite of fetch-skip, and will only do the fetch step

**Comment by bootradev** [comment]
Hey there! As of https://github.com/bootradev/zig-fetch/commit/bebce6cf40499c9d42ae1c60d22aca16f1004994, recursive fetching and the additional fetch build options should resolve this issue.

In particular:

There are now three build options you can pass into `zig build`. 
1. `fetch-skip` - skips fetching entirely
2. `fetch-only` - only fetches, doesn't build
3. `fetch-force` - forces fetching to happen, even if the dependencies exist in the cache

Additionally, fetching is now recursive - if a dependency is using `zig-fetch`, it will be built with `-Dfetch-only=true` during the fetch phase.

Please let me know if this satisfies the issue! Thanks again for filing!

**Comment by bootradev** [comment]
I'm going to go ahead and close the issue - feel free to reopen it if you have unresolved concerns!
