### ISSUE TITLE
Check/ensure "git" is installed before invoking it

### ISSUE THREAD

**Issue by emidoots** [bootradev/zig-fetch#2]
As crazy as it is, many who switch between WSL and non-WSL on Windows (or those who use Git GUIs instead of the CLI) often do not have it on their path. I've had reports of users of Mach engine not having Git, so producing a nice error in this case is desirable.

We use this function in Mach to do it: https://github.com/hexops/mach/blob/47d1544b6483ec6038fcc0eb2b90c14f8ab8d253/build.zig#L419-L437

**Comment by bootradev** [comment]
Great suggestion! This is now implemented in https://github.com/bootradev/zig-fetch/commit/a4f64c2bed3ef9023468e5b8041577fe89a1034f
