### ISSUE TITLE
Figure out how to pass through step/options

### ISSUE THREAD

**Issue by desttinghim** [bootradev/zig-fetch#3]
This isn't something I've managed to solve yet. Zig checks to make sure that the step and options passed to zig build  exist in `build.zig`. This is important because it is common for libraries to define multiple steps for building and running examples.

**Comment by bootradev** [comment]
What are some examples of where this is failing with the current code? The command line you pass to the first zig build is passed to the second zig build.

**Comment by desttinghim** [comment]
```sh
[desttinghim@nixos:~/Code/machlibs/synth]$ zig build run-example-wasm4-apu
error: Cannot run step 'run-example-wasm4-apu' because it does not exist
Usage: /nix/store/2q2cwzvnh655b2f8machs1wxyix5083h-zig-0.10.0-dev.3952+9e070b653/bin/zig build [steps] [options]

# Rest of usage message snipped
```

**Comment by bootradev** [comment]
Ah I see the problem, thanks! I'll do some thinking on this.

**Comment by desttinghim** [comment]
It may be something that needs to be handled in zig proper for the experience to be seamless

**Comment by bootradev** [comment]
Perhaps we provide a way to easily pass in no-op steps when calling fetchAndBuild

**Comment by bootradev** [comment]
Could you take a look at https://github.com/bootradev/zig-fetch/commit/2252507dc0f84a7dd87b8bc8fc99b9c4ce7fd12c and see if that resolves the issue for you?

**Comment by desttinghim** [comment]
Yes, that works. Thanks for implementing this!
